services:
  valeska-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valeska_central_api
    restart: unless-stopped
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      REQUEST_BODY_LIMIT: ${REQUEST_BODY_LIMIT:-10mb}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      SYNC_QUEUE_CONCURRENCY: ${SYNC_QUEUE_CONCURRENCY:-5}
      DESKTOP_UPDATES_DIR: storage/desktop-updates/files
      DESKTOP_UPDATES_MANIFEST: storage/desktop-updates/releases.json
      DESKTOP_UPDATES_PUBLIC_BASE_URL: https://valeska-api.studios-tkoh.online
    depends_on:
      - redis
    networks:
      - valeska_shared_net
    volumes:
      - ./storage:/app/storage

  redis:
    image: redis:7-alpine
    container_name: valeska_redis
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - valeska_redis_data:/data
    networks:
      - valeska_shared_net

networks:
  valeska_shared_net:
    external: true

volumes:
  valeska_redis_data:
